# must be run on root
FROM node:18-alpine

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

WORKDIR /app

COPY package*.json ./
RUN yarn install

COPY . .

EXPOSE 3000

CMD ["./deploy/entrypoint.editor.sh"]

